env:
  TERM: screen-256color

draw_bold_text_with_bright_colors: true

live_config_reload: true

bell:
  duration: 0

# Colors
colors:
  # Default colors
  primary:
    background: '#131313'
    foreground: '#cfd2d0'

  # Normal colors
  normal:
    black:   '#000000'
    red:     '#ff7ef3'
    green:   '#97cb9b'
    yellow:  '#ffdebe'
    blue:    '#96cbfe'
    magenta: '#c6c5fd'
    cyan:    '#96cbfe'
    white:   '#e6e6e6'

  # Bright colors
  bright:
    black:   '#000000'
    red:     '#ff7ef3'
    green:   '#a2f644'
    yellow:  '#f7fcb6'
    blue:    '#a5d5fe'
    magenta: '#c6c5fd'
    cyan:    '#96cbfe'
    white:   '#e6e6e6'

font:
  use_thin_strokes: true
  normal:
    family: "FuraCode Nerd Font Mono"
    style: Light
  bold:
    family: "FuraCode Nerd Font Mono"
    style: Regular
  size: 11

mouse:
  hide_when_typing: true

selection:
  save_to_clipboard: true

cursor:
  unfocused_hollow: true
