env:
  TERM: xterm-256color

# Colors
colors:
  # Default colors
  primary:
    background: '#131313'
    foreground: '#cfd2d0'

  # Normal colors
  normal:
    black:   '#000000'
    red:     '#ff7ef3'
    green:   '#97cb9b'
    yellow:  '#ffdebe'
    blue:    '#a5d5fe'
    magenta: '#c6c5fd'
    cyan:    '#96cbfe'
    white:   '#e6e6e6'

  # Bright colors
  bright:
    black:   '#000000'
    red:     '#ff7ef3'
    green:   '#a2f644'
    yellow:  '#ffdebe'
    blue:    '#a5d5fe'
    magenta: '#c6c5fd'
    cyan:    '#96cbfe'
    white:   '#e6e6e6'

font:
  normal:
    family: "FuraCode Nerd Font Mono"
    style: Regular
  size: 12
