draw_bold_text_with_bright_colors: true

live_config_reload: true

bell:
  duration: 0

# Colors
schemes:
  gruvbox_dark: &gruvbox_dark
    primary:
      background: '0x1d2021'
      foreground: '0xf9f5d7'

    normal:
      black:   '0x665c54'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xe78a4e'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xdfbf8e'

    bright:
      black:   '0x928374'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xe3a84e'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xdfbf8e'


  gruvbox_light: &gruvbox_light
    primary:
      background: '0xf9f5d7'
      foreground: '0x1d2021'

    normal:
      black:   '0xbdae93'
      red:     '0xcc241d'
      green:   '0x98971a'
      yellow:  '0xd79921'
      blue:    '0x458588'
      magenta: '0xb16286'
      cyan:    '0x689d6a'
      white:   '0xdfbf8e'

    bright:
      black:   '0x7c6f64'
      red:     '0xfb4934'
      green:   '0xb8bb26'
      yellow:  '0xfabd2f'
      blue:    '0x83a598'
      magenta: '0xd3869b'
      cyan:    '0x8ec07c'
      white:   '0xdfbf8e'

colors: *gruvbox_light

font:
  use_thin_strokes: true
  normal:
    family: "SauceCodePro Nerd Font"
    style: "Regular"
  bold:
    family: "SauceCodePro Nerd Font"
    style: "Medium"
  italic:
    family: "SauceCodePro Nerd Font"
    style: "Italic"
  size: 13
  offset:
   x: 0 # letter spacing
   y: 0 # line spacing

mouse:
  hide_when_typing: true

selection:
  save_to_clipboard: true

cursor:
  unfocused_hollow: true

key_bindings:
  - { key: Left,     mods: Alt,     chars: "\x1bb"                       } # Skip word left
  - { key: Right,    mods: Alt,     chars: "\x1bf"                       } # Skip word right
  - { key: Left,     mods: Command, chars: "\x1bOH",   mode: AppCursor   } # Home
  - { key: Right,    mods: Command, chars: "\x1bOF",   mode: AppCursor   } # End
  - { key: Back,     mods: Command, chars: "\x15"                        } # Delete line
  - { key: Back,     mods: Alt,     chars: "\x1b\x7f"                    } # Delete word
  - { key: D,        mods: Alt,     chars: "\x1bd"                       }
