[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Alt"

[general]
import = ["~/.config/alacritty/themes/one-dark.toml"]
live_config_reload = true

[bell]
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = true

[font]
size = 14

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Medium"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 2

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[keyboard]
