draw_bold_text_with_bright_colors: true

live_config_reload: true

bell:
  duration: 0

# Colors
colors:
  # Default colors
  primary:
    background: '#131313'
    foreground: '#cfd2d0'

  # Normal colors
  normal:
    black:   '#000000'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#e5c07b'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#abb2bf'

  # Bright colors
  bright:
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#e5c07b'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#abb2bf'

font:
  use_thin_strokes: true
  normal:
    family: "SauceCodePro Nerd Font"
    style: "Regular"
  bold:
    family: "SauceCodePro Nerd Font"
    style: "Medium"
  italic:
    family: "SauceCodePro Nerd Font"
    style: "Italic"
  size: 13
  offset:
   x: 0 # letter spacing
   y: 0 # line spacing

mouse:
  hide_when_typing: true

selection:
  save_to_clipboard: true

cursor:
  unfocused_hollow: true

key_bindings:
  - { key: Left,     mods: Alt,     chars: "\x1bb"                       } # Skip word left
  - { key: Right,    mods: Alt,     chars: "\x1bf"                       } # Skip word right
  - { key: Left,     mods: Command, chars: "\x1bOH",   mode: AppCursor   } # Home
  - { key: Right,    mods: Command, chars: "\x1bOF",   mode: AppCursor   } # End
  - { key: Back,     mods: Command, chars: "\x15"                        } # Delete line
  - { key: Back,     mods: Alt,     chars: "\x1b\x7f"                    } # Delete word
  - { key: D,        mods: Alt,     chars: "\x1bd"                       }
