# taps
tap "tmatilai/terraforms"
tap "oven-sh/bun"

# hashicorp/tap is deliberately absent. It fails Homebrew's tap-time validation
# (Formula/vagrant.rb defines no url outside Linux/intel; its casks wrap
# everything in `on_macos` without `depends_on :macos`), and the packer and
# terraform kegs here came from homebrew/core, which brew refuses to reinstall
# from a different tap. Both stay installed as-is; terraform versions come from
# chtf. To restore: brew uninstall packer terraform &&
# HOMEBREW_DEVELOPER=1 brew tap hashicorp/tap

# applications
cask "session-manager-plugin"
cask "font-sauce-code-pro-nerd-font"
cask "claude-code"

# packages
brew "autoconf"
brew "bat"
brew "diff-so-fancy"
brew "dnsmasq"
brew "fzf"
brew "git"
brew "git-lfs"
brew "gnupg2"
brew "highlight"
brew "gh"
brew "ipython"
brew "jq"
brew "markdown"
brew "neovim"
brew "node"
brew "oven-sh/bun/bun"
brew "keychain"
brew "pinentry"
brew "pinentry-mac"
brew "reattach-to-user-namespace"
brew "the_silver_searcher"
brew "shellcheck"
brew "tmux"
brew "herdr"
brew "trash"
brew "tree"
brew "wget"
brew "z"
brew "zsh"
brew "ripgrep"
brew "entr"
brew "docker"
brew "colima"
brew "awscli"
brew "direnv"
brew "ansible"
brew "tmatilai/terraforms/chtf"
brew "pstree"
brew "dive"
brew "k6"
brew "grip"
brew "lnav"
brew "coreutils"
brew "gawk"
brew "asdf"
brew "languagetool"
brew "cfn-lint"
brew "elixir"
brew "java"
brew "htop"
brew "pyenv"
brew "pyenv-virtualenv"
brew "openblas"
brew "lapack"
brew "go"
brew "libpq"
brew "mysql-client"
brew "pixman"
brew "cairo"
brew "pango"
brew "poetry"
brew "azure-cli"
brew "tree-sitter"
brew "tree-sitter-cli"
brew "fd"
brew "lazygit"
